### ISSUE TITLE
VCRTestCase does not work if your test case has a setUp

### ISSUE THREAD

**Issue by mandshaw** [agriffis/vcrpy-unittest#6]
Hey,

Firstly AWESOME Package, very very very cool

I had a test case which was full of mocks and patches and I am lazy so pulled them out and replaced them. The tests needs some common stuff though so I had a setUp which setup some os.environ variables.

Then VCRTestCase stopped working.

Took me awhile to figure out but turns out if you have a setup then vcr-unittest doesnt work!

No idea why yet!

**Comment by mandshaw** [comment]
Ah I see now. If you want to use a setUp you have to call the parent class setUp as well

**Comment by lynncyrin** [comment]
Just ran into this same issue >_> +1 user error
